valepredict/previsoes/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'previsao'

urlpatterns = [
    path('', views.home, name='home'),
    path('calcular/', views.calcular_previsao, name='calcular_previsao'),
    path('login/', auth_views.LoginView.as_view(template_name='previsoes/login.html'), name='login'),
    path('register/', views.register, name='register'),
]

valepredict/valepredict/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('previsoes.urls')),
]

valepredict/previsoes/models.py
from django.db import models

class DadosAgricolas(models.Model):
    estado = models.CharField(max_length=100, blank=True, null=True) 
    regiao = models.CharField(max_length=100, blank=True, null=True) 
    cultura = models.CharField(max_length=100)  
    area = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True) 
    valor = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True) 

    def calcular_valor_por_hectare(self):
        """
        Retorna o valor por hectare se os dados estiverem disponíveis.
        """
        if self.area and self.valor:
            return self.valor / self.area
        return None

    def calcular_lucro(self, area_usuario):
        """
        Calcula o lucro baseado na área informada pelo usuário.
        """
        valor_por_hectare = self.calcular_valor_por_hectare()
        if valor_por_hectare:
            return valor_por_hectare * area_usuario
        return None

    def __str__(self):
        if self.estado:
            return f"{self.estado} - {self.cultura}"
        if self.regiao:
            return f"{self.regiao} - {self.cultura}"
        return self.cultura

valepredict/previsoes/forms.py
from django import forms
from .models import DadosAgricolas

class PrevisaoForm(forms.Form):
    nome_cultura = forms.ModelChoiceField(queryset=DadosAgricolas.objects.all(), 
                                          to_field_name='cultura', 
                                          label="Escolha a cultura")
    area = forms.DecimalField(label="Área disponível para plantio (hectares)", max_digits=10, decimal_places=2)

valepredict/previsoes/views.py
from django.shortcuts import render
from .forms import PrevisaoForm
from .models import DadosAgricolas
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required


def home(request):
    return render(request, 'previsoes/home.html')

@login_required(login_url='previsoes/login.html')
def calcular_previsao(request):
    if request.method == "POST":
        form = PrevisaoForm(request.POST)
        if form.is_valid():
            dados_cultura = form.cleaned_data['nome_cultura']
            area = form.cleaned_data['area']

            if dados_cultura:
                # Calculando o lucro com base nos dados da cultura
                lucro_estimado = dados_cultura.calcular_lucro(area)

                return render(request, 'previsoes/resultado.html', {
                    'nome_cultura': dados_cultura.cultura,
                    'area': area,
                    'lucro_estimado': lucro_estimado,
                    'valor_por_hectare': dados_cultura.calcular_valor_por_hectare(),
                })
            else:
                return render(request, 'previsoes/erro.html', {'mensagem': 'Cultura não encontrada no banco de dados.'})
    else:
        form = PrevisaoForm()

    return render(request, 'previsoes/calcular.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'previsoes/register.html', {'form': form})

valepredict/previsoes/templates/previsoes/calcular.html
{%load static%}

<!DOCTYPE html>
<html>
<head>
    <title>Previsão de Lucro</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Previsão</title>
</head>
<body>
    
    <div class = 'container'> 
        <h1>Previsão de Lucro</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Calcular</button>
        </form>
    </div>
</body>
</html>

valepredict/previsoes/templates/previsoes/erro.html
<!DOCTYPE html>
<html>
<head>
    <title>Erro</title>
</head>
<body>
    <h1>Erro</h1>
    <p>{{ erro }}</p>
    <a href="{% url 'previsao:calcular_previsao' %}">Voltar</a>
</body>
</html>

valepredict/previsoes/templates/previsoes/home.html
{%load static%}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>ValePredict</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div style="background-color: #004d33; color: white; padding: 20px;">
        <h1>ValePredict</h1>
        <p>Imagine saber, antes de iniciar...</p>
        <a href="{% url 'previsao:calcular_previsao' %}" style="background: orange; padding: 10px; color: white; text-decoration: none;">Comece já</a>
    </div>
</body>
</html>

valepredict/previsoes/templates/previsoes/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/credentials.css' %}">
</head>
<body>
    <div>
        <form method="POST">
            {% csrf_token %}
            <h1>Login</h1>
            <input type="email" name="email" placeholder="Digite seu e-mail" required>
            <input type="password" name="password" placeholder="Digite sua senha" required>
            <button type="submit">Entrar</button>
            <a href="{% url 'previsao:register' %}">Não tem uma conta? Cadastre-se</a>
        </form>
    </div>
</body>
</html>

valepredict/previsoes/templates/previsoes/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Cadastro</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/credentials.css' %}">
</head>
<body>
    <div>
        <form method="POST">
            {% csrf_token %}
            <h1>Cadastro</h1>
            <input type="text" name="username" placeholder="Digite seu nome de usuário" required>
            <input type="email" name="email" placeholder="Digite seu e-mail" required>
            <input type="password" name="password1" placeholder="Digite sua senha" required>
            <input type="password" name="password2" placeholder="Confirme sua senha" required>
            <button type="submit">Cadastrar</button>
            <a href="{% url 'previsao:login' %}">Já tem uma conta? Faça login</a>
        </form>
    </div>
</body>
</html>

valepredict/previsoes/templates/previsoes/resultado.html
<!DOCTYPE html>
<html>
<head>
    <title>Resultado da Previsão</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class = 'container'>
        <h1>Resultado da Previsão de Lucro</h1>

        <p><strong>Cultura:</strong> {{ nome_cultura }}</p>
        <p><strong>Área disponível para plantio:</strong> {{ area }} hectares</p>
        <p><strong>Área plantada:</strong> {{ area_plantada }} hectares</p>
        <p><strong>Valor da produção:</strong> R$ {{ valor_producao }}</p>
        <p><strong>Custo estimado:</strong> R$ {{ custo }}</p>
        <p><strong>Lucro estimado:</strong> R$ {{ lucro_estimado }}</p>
        <p><strong>Prejuízo estimado:</strong> R$ {{ prejuizo_estimado }}</p>

        <a href="{% url 'previsao:calcular_previsao' %}">Voltar</a>
    </div>
</body>
</html>